profile_links:
  default: 'activity|messages'
  type: list
  allow_any: false
  list_type: compact
  choices:
    - summary
    - activity
    - messages
    - invites
    - drafts
    - preferences
  description:
    en: "Profile links in widget. Accepts: summary, activity, messages, invites, drafts, preferences"